name: Deploy to EC2

on:
  push:
    branches:
      - main   # Runs only when code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build & Push Docker image
      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/skysoft-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/skysoft-app:latest

      # Step 4: Deploy to EC2 via SSH
      - name: SSH into EC2 & Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Stop and remove old container
            docker stop skysoft || true
            docker rm skysoft || true

            # Pull latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/skysoft-app:latest

            # Run new container
            docker run -d --name skysoft -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/skysoft-app:latest
